[package]
name = "penguin-downloader"
version = "4.0.0"
edition = "2021"
license = "MIT"
authors = ["DeeChael"]
repository = "https://github.com/DeeChael/penguin-downloader"
description = "A music downloader core library."
exclude = ["test", ".git", ".idea"]

[dependencies]
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["stream"] }
tokio = { version = "1", features = ["fs", "io-util"] }
tokio-stream = "0.1"
futures-util = "0.3"
thiserror = "2"
